name: 'Dependabot auto-merge'
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'Tailormap/tailormap-api'
    steps:
      - name: 'Fetch Dependabot metadata'
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Enable auto-merge for Dependabot PRs on geoserver, tomcat, oracle-free, postgis, solr and mssql dependencies for patch and minor version updates'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: |
          ( 
            contains(steps.metadata.outputs.dependency-names, 'geoserver') ||
            contains(steps.metadata.outputs.dependency-names, 'tomcat') ||
            contains(steps.metadata.outputs.dependency-names, 'oracle-free') ||
            contains(steps.metadata.outputs.dependency-names, 'postgis') ||
            contains(steps.metadata.outputs.dependency-names, 'solr') ||
            contains(steps.metadata.outputs.dependency-names, 'mssql')
          ) && (
            steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
            steps.metadata.outputs.update-type == 'version-update:semver-minor'
          )
        run: |
          gh pr edit --remove-label "infrastructure" "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
      - name: 'Enable auto-merge for Dependabot PRs on Maven plugins and GH actions for patch and minor version updates'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: |
          (
            contains(steps.metadata.outputs.dependency-names, 'maven') ||
            contains(steps.metadata.outputs.dependency-names, 'action')
          ) && (
            steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
            steps.metadata.outputs.update-type == 'version-update:semver-minor'
          )
        run: |
          gh pr edit --remove-label "dependency" "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"

